### ISSUE TITLE
Hello, when will you release the rest of the code and data?

### ISSUE THREAD

**Issue by weikang-wang** [UKPLab/arxiv2023-sociodemographic-prompting#1]

**Comment by tilmanbeck** [comment]
Hi @weikang-wang ,

sorry for my late answer and thanks for pointing out the missing code! I will upload the full code on the weekend.

Thanks for your patience.

Best Regards,
Tilman

**Comment by Sooyonglee** [comment]
Hi, I believe that there is still some code missing from the repo. Will this be added soon?

**Comment by tilmanbeck** [comment]
@weikang-wang @tilmanbeck Please have a look at the updated code.
